export const environment = {
  ctp_project_key: 'e-commerce-coffee-shop',
  ctp_client_secret: 'lUCejXyX065BeoPZA4Y2xw_eIWwtk3rl',
  ctp_client_id: 'd3f3nz6eXCmQc8Y5qaknACk-',
  ctp_auth_url: 'https://auth.eu-central-1.aws.commercetools.com',
  ctp_api_url: 'https://api.eu-central-1.aws.commercetools.com',
  ctp_scopes: [
    'view_tax_categories:e-commerce-coffee-shop',
    'manage_sessions:e-commerce-coffee-shop',
    'view_project_settings:e-commerce-coffee-shop',
    'view_cart_discounts:e-commerce-coffee-shop',
    'manage_order_edits:e-commerce-coffee-shop',
    'view_products:e-commerce-coffee-shop',
    'view_product_selections:e-commerce-coffee-shop',
    'manage_shopping_lists:e-commerce-coffee-shop',
    'view_discount_codes:e-commerce-coffee-shop',
    'view_published_products:e-commerce-coffee-shop',
    'view_types:e-commerce-coffee-shop',
    'manage_orders:e-commerce-coffee-shop',
    'view_standalone_prices:e-commerce-coffee-shop',
    'view_sessions:e-commerce-coffee-shop',
    'manage_customers:e-commerce-coffee-shop',
    'view_shipping_methods:e-commerce-coffee-shop',
    'view_categories:e-commerce-coffee-shop',
    'create_anonymous_token:e-commerce-coffee-shop',
  ],
};
